#!/usr/bin/env bash
# ============================================================
# StreamBazaar multi-node launcher
#
# Usage:
#   NODE_COUNT=4 bash scripts/run-distributed.sh [start|stop|status]
#   NODE_COUNT=8 INFRA_HOST=192.168.1.10 bash scripts/run-distributed.sh start
#
# Supported NODE_COUNT values: 1 2 4 6 8 10 12 16
#
# What this script does:
#   1. Validates NODE_COUNT
#   2. Computes per-node tenant assignments
#   3. Ensures Kafka topics have enough partitions (1 per shard)
#   4. Writes per-node docker-compose override files
#   5. Starts infra services (once), then N worker instances
#
# Single-machine mode (default):  all nodes as separate Docker containers
# Swarm mode:  set SWARM=1 and ensure `docker swarm init` is done first
# ============================================================

set -euo pipefail

NODE_COUNT="${NODE_COUNT:-1}"
INFRA_HOST="${INFRA_HOST:-localhost}"
KAFKA_BOOTSTRAP="${KAFKA_BOOTSTRAP:-${INFRA_HOST}:19092}"   # external port
REDIS_URL="${REDIS_URL:-redis://${INFRA_HOST}:6379/0}"
SCHEDULER_MODE="${SCHEDULER_MODE:-streambazaar}"
ACTION="${1:-start}"
SWARM="${SWARM:-0}"
COMPOSE="docker compose"

# ── Validate node count ────────────────────────────────────────────────────
VALID_COUNTS=(1 2 4 6 8 10 12 16)
valid=0
for v in "${VALID_COUNTS[@]}"; do [[ "$NODE_COUNT" -eq "$v" ]] && valid=1 && break; done
if [[ "$valid" -eq 0 ]]; then
  echo "ERROR: NODE_COUNT must be one of: ${VALID_COUNTS[*]}"
  exit 1
fi

# ── Full tenant list (add more as needed) ─────────────────────────────────
ALL_TENANTS=(
  tenant-fraud tenant-clickstream tenant-ml tenant-iot
  tenant-fraud-2 tenant-web tenant-intrusion tenant-iot-2
  tenant-fraud-3 tenant-clickstream-3 tenant-ml-3 tenant-iot-3
  tenant-fraud-4 tenant-clickstream-4 tenant-ml-4 tenant-iot-4
)

# Use first NODE_COUNT*2 tenants so each node gets at least 2
TOTAL_TENANTS=$(( NODE_COUNT < 4 ? 4 : NODE_COUNT * 2 ))
TOTAL_TENANTS=$(( TOTAL_TENANTS > ${#ALL_TENANTS[@]} ? ${#ALL_TENANTS[@]} : TOTAL_TENANTS ))
TENANTS=("${ALL_TENANTS[@]:0:$TOTAL_TENANTS}")

# ── Assign tenants to nodes ───────────────────────────────────────────────
declare -A NODE_TENANTS
for (( i=0; i<TOTAL_TENANTS; i++ )); do
  node_id=$(( i % NODE_COUNT ))
  if [[ -z "${NODE_TENANTS[$node_id]+_}" ]]; then
    NODE_TENANTS[$node_id]="${TENANTS[$i]}"
  else
    NODE_TENANTS[$node_id]="${NODE_TENANTS[$node_id]},${TENANTS[$i]}"
  fi
done

echo "=================================================="
echo " StreamBazaar  nodes=${NODE_COUNT}  mode=${SCHEDULER_MODE}"
echo " infra=${INFRA_HOST}  kafka=${KAFKA_BOOTSTRAP}"
echo "=================================================="
for (( n=0; n<NODE_COUNT; n++ )); do
  echo "  node-${n}: ${NODE_TENANTS[$n]}"
done
echo ""

OVERRIDES_DIR="deployment/node-overrides"
mkdir -p "$OVERRIDES_DIR"

# ── Generate per-node self-contained compose files ────────────────────────
# Each worker node gets its own compose file + project name (sb-node-N) so
# they can run independently alongside the shared infra project (streambazaar).
# An external network reference connects each worker project to the infra network.
for (( n=0; n<NODE_COUNT; n++ )); do
  TENANTS_FOR_NODE="${NODE_TENANTS[$n]}"
  PORT_OFFSET=$(( n * 10 ))          # spread ports so all nodes fit on one machine
  SC_PORT=$(( 18085 + PORT_OFFSET ))
  PE_PORT=$(( 18081 + PORT_OFFSET ))

  # Use internal docker names for infra when running on single machine
  if [[ "${INFRA_HOST}" == "localhost" ]]; then
    KAFKA_INTERNAL="kafka:9092"
    REDIS_INTERNAL="redis://redis:6379/0"
    BID_HOST="auction-orchestrator:8080"
    CLEAR_HOST="auction-orchestrator:8080"
  else
    KAFKA_INTERNAL="${KAFKA_BOOTSTRAP}"
    REDIS_INTERNAL="${REDIS_URL}"
    BID_HOST="${INFRA_HOST}:18080"
    CLEAR_HOST="${INFRA_HOST}:18080"
  fi

  cat > "${OVERRIDES_DIR}/node-${n}.yml" <<EOF
# Auto-generated by run-distributed.sh  node=${n}/${NODE_COUNT}
# Self-contained worker compose — project name: sb-node-${n}
networks:
  infra:
    external: true
    name: streambazaar_default

services:
  stream-coordinator:
    build: ./services/stream-coordinator
    container_name: sb-stream-coordinator-node${n}
    networks: [infra]
    ports:
      - "${SC_PORT}:8085"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_INTERNAL}
      REDIS_URL: ${REDIS_INTERNAL}
      TENANT_IDS: ${TENANTS_FOR_NODE}
      SCHEDULER_MODE: ${SCHEDULER_MODE}
      COORDINATOR_GROUP_ID: stream-coordinator-node${n}
      NODE_ID: "${n}"
      CLUSTER_SLOTS: "30"
      PRICING_URL: http://sb-pricing-engine-node${n}:8081/price
      BID_URL: http://${BID_HOST}/bid
      CLEAR_URL: http://${CLEAR_HOST}/auction/clear
      ALLOCATE_URL: http://sb-resource-allocator-node${n}:8083/allocate
      MIGRATE_URL: http://sb-migration-coordinator-node${n}:8084/migrate

  pricing-engine:
    build: ./services/pricing-engine
    container_name: sb-pricing-engine-node${n}
    hostname: sb-pricing-engine-node${n}
    networks: [infra]
    ports:
      - "${PE_PORT}:8081"
    environment:
      REDIS_URL: ${REDIS_INTERNAL}

  resource-allocator:
    build: ./services/resource-allocator
    container_name: sb-resource-allocator-node${n}
    hostname: sb-resource-allocator-node${n}
    networks: [infra]

  migration-coordinator:
    build: ./services/migration-coordinator
    container_name: sb-migration-coordinator-node${n}
    hostname: sb-migration-coordinator-node${n}
    networks: [infra]
EOF
done

# ── Helper: create Kafka topics with right partition count ────────────────
create_topics() {
  echo "[kafka] creating topics with ${NODE_COUNT} partitions …"
  TENANT_CSV=""
  for t in "${TENANTS[@]}"; do
    TENANT_CSV="${TENANT_CSV}${t},"
  done
  TENANT_CSV="${TENANT_CSV%,}"

  docker compose exec -T kafka kafka-topics \
    --bootstrap-server kafka:9092 \
    --create --if-not-exists \
    --topic streamBazaar.bids \
    --partitions "$NODE_COUNT" --replication-factor 1 2>/dev/null || true

  for topic in streamBazaar.allocations streamBazaar.preemptions streamBazaar.metrics; do
    docker compose exec -T kafka kafka-topics \
      --bootstrap-server kafka:9092 \
      --create --if-not-exists \
      --topic "$topic" \
      --partitions "$NODE_COUNT" --replication-factor 1 2>/dev/null || true
  done

  IFS=',' read -ra TA <<< "$TENANT_CSV"
  for t in "${TA[@]}"; do
    for suffix in input output; do
      docker compose exec -T kafka kafka-topics \
        --bootstrap-server kafka:9092 \
        --create --if-not-exists \
        --topic "tenant.${t}.${suffix}" \
        --partitions "$NODE_COUNT" --replication-factor 1 2>/dev/null || true
    done
  done
  echo "[kafka] topics ready"
}

# ── Actions ───────────────────────────────────────────────────────────────
case "$ACTION" in

  start)
    echo "[1/4] Starting infrastructure services …"
    # Stop any leftover single-node worker services that would conflict with
    # per-node workers (same ports, same container names).
    $COMPOSE stop stream-coordinator pricing-engine resource-allocator migration-coordinator 2>/dev/null || true
    $COMPOSE rm -f stream-coordinator pricing-engine resource-allocator migration-coordinator 2>/dev/null || true

    $COMPOSE up -d --build \
      zookeeper kafka redis postgres \
      auction-orchestrator prometheus grafana tenant-manager

    # prometheus depends_on pricing-engine — stop it if it snuck in
    $COMPOSE stop pricing-engine resource-allocator migration-coordinator stream-coordinator 2>/dev/null || true
    $COMPOSE rm -f pricing-engine resource-allocator migration-coordinator stream-coordinator 2>/dev/null || true

    echo "[2/4] Waiting for Kafka …"
    until docker compose exec -T kafka kafka-topics \
        --bootstrap-server kafka:9092 --list &>/dev/null; do
      echo "  kafka not ready yet …"; sleep 2
    done

    echo "[3/4] Creating Kafka topics (${NODE_COUNT} partitions) …"
    create_topics

    echo "[4/4] Starting ${NODE_COUNT} worker node(s) …"
    for (( n=0; n<NODE_COUNT; n++ )); do
      echo "  starting node-${n} (tenants: ${NODE_TENANTS[$n]}) …"
      $COMPOSE \
        --project-directory "$(pwd)" \
        -p "sb-node-${n}" \
        -f "${OVERRIDES_DIR}/node-${n}.yml" \
        up -d --build
    done

    echo ""
    echo "✓ StreamBazaar running on ${NODE_COUNT} node(s)"
    echo "  Prometheus : http://localhost:19090"
    echo "  Grafana    : http://localhost:13000"
    for (( n=0; n<NODE_COUNT; n++ )); do
      SC_PORT=$(( 18085 + n * 10 ))
      echo "  node-${n} health: http://localhost:${SC_PORT}/health"
    done
    ;;

  stop)
    echo "Stopping all StreamBazaar services …"
    for (( n=0; n<NODE_COUNT; n++ )); do
      $COMPOSE \
        --project-directory "$(pwd)" \
        -p "sb-node-${n}" \
        -f "${OVERRIDES_DIR}/node-${n}.yml" \
        down 2>/dev/null || true
    done
    $COMPOSE down 2>/dev/null || true
    echo "Stopped."
    ;;

  status)
    echo "=== Docker containers ==="
    docker ps --filter "name=sb-" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
    echo ""
    echo "=== Health endpoints ==="
    for (( n=0; n<NODE_COUNT; n++ )); do
      SC_PORT=$(( 18085 + n * 10 ))
      STATUS=$(curl -fsS "http://localhost:${SC_PORT}/health" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('scheduler_mode','?'), 'tenants='+str(d.get('tenants','?')), 'running='+str(d.get('running','?')))" 2>/dev/null || echo "unreachable")
      echo "  node-${n} :${SC_PORT} — ${STATUS}"
    done
    ;;

  *)
    echo "Usage: NODE_COUNT=N bash $0 [start|stop|status]"
    exit 1
    ;;
esac
